# Generated by Django 5.2.5 on 2025-08-12 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('borrow_record', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='book.book'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='return_date',
            field=models.DateTimeField(null=True),
        ),
    ]
