# Generated by Django 5.2.5 on 2025-08-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='membership_date',
            field=models.DateTimeField(max_length=255, null=True),
        ),
    ]
